import { ENVSchema } from "@/auth/envSchema";
import { Dimensions } from "react-native"
import { RFPercentage } from "react-native-responsive-fontsize";


export const {
    ZERO_ENCRYPTION_KEY,
    SUPPORT_PHONE_NUMBER,
    SUPPORT_EMAIL,
    MAIN_SERVER_URL,
    NOTIFICATION_SERVER_URL,
    AUTHENTICATION_SERVER_URL,
    AZURE_FACE_API_ENDPOINT,
    AZURE_FACE_API_KEY,
    NODEMAILER_EMAIL,
    NODEMAILER_PASSWORD,
    OCR_SPACE_API_KEY,
    CLOUDINARY_API_KEY,
    CLOUDINARY_SECRET_KEY,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_ID_UPLOAD_PRESET,
    CLOUDINARY_VIDEO_UPLOAD_PRESET,
    CLOUDINARY_API_URL,
    CLOUDINARY_AUDIO_API_URL,
    GOOGLE_MAPS_API_KEY
} = ENVSchema.evironmentVariables.parse(process.env)



export const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window")
export const TEXT_HEADING_FONT_SIZE = RFPercentage(4)
export const TEXT_PARAGRAPH_FONT_SIZE = RFPercentage(1.75)
export const INPUT_HEIGHT = SCREEN_HEIGHT < 670 ? RFPercentage(6) + 8 : RFPercentage(6)
export const TEXTAREA_HEIGHT = SCREEN_HEIGHT < 670 ? RFPercentage(15) + 8 : RFPercentage(15)
export const INPUT_CODE_HEIGHT = SCREEN_HEIGHT < 670 ? RFPercentage(7) : RFPercentage(6)


export const DATABASE_NAME = "db.db"
export const SOCKET_EVENTS = {
    CONNECT: "connect",
    DISCONNECT: "disconnect",
    TRANSACTION_CREATED: "TRANSACTION_CREATED",
    TRANSACTION_REQUEST_PAIED: "TRANSACTION_REQUEST_PAIED",
    TRANSACTION_CREATED_FROM_QUEUE: "TRANSACTION_CREATED_FROM_QUEUE",
    TRANSACTION_REQUEST_CANCELED: "TRANSACTION_REQUEST_CANCELED",

    NOTIFICATION_TRANSACTION_CREATED: "NOTIFICATION_TRANSACTION_CREATED",
    NOTIFICATION_TRANSACTION_REQUEST_PAIED: "NOTIFICATION_TRANSACTION_REQUEST_PAIED",
    NOTIFICATION_BANKING_TRANSACTION_CREATED: "NOTIFICATION_BANKING_TRANSACTION_CREATED",
    NOTIFICATION_LOGIN_VERIFICATION_CODE: "NOTIFICATION_LOGIN_VERIFICATION_CODE",
    NOTIFICATION_TRANSACTION_CREATED_FROM_QUEUE: "NOTIFICATION_TRANSACTION_CREATED_FROM_QUEUE",
    NOTIFICATION_TRANSACTION_REQUEST_CANCELED: "NOTIFICATION_TRANSACTION_REQUEST_CANCELED",
    NOTIFICATION_QUEUE_TRANSACTION_CREATED: "NOTIFICATION_QUEUE_TRANSACTION_CREATED",
}
