version: '3.4'

services:
  # main-server:
  main-server:
    image: main-server
    build:
      context: main-back-end
      dockerfile: Dockerfile
    env_file: ./main-back-end/.env
    # depends_
    
    volumes:
      - ./main-back-end:/app
      - /node_modules
    command: npm run dev dev
    ports:
      - 8000:8000

  # # notification-server:
  # notification-server:
  #   image: notification-server
  #   build:
  #     context: notification
  #     dockerfile: Dockerfile
  #   env_file: ./notification/.env
  #   # depends_on:
  #   #   - postgres
  #   volumes:
  #     - ./notification-back-end:/app
  #     - /node_modules
  #   command: npm run dev
  #   ports:
  #     - 8000:8000
  #   restart: always





