import { GlobalZodSchema } from "@/auth"


const evironmentVariables = GlobalZodSchema.evironmentVariables.parse(process.env)
export const {
    PORT,
    REDIS_HOST,
    REDIS_PORT,
    SESSION_SECRET_SECRET_KEY,
    ZERO_ENCRYPTION_KEY,
    AUTH_SERVER_URL,
    NOTIFICATION_SERVER_URL,
    ZERO_SIGN_PRIVATE_KEY,
    QUEUE_SERVER_URL

} = evironmentVariables


export const REDIS_SUBSCRIPTION_CHANNEL = {
    TRANSACTION_CREATED: "TRANSACTION_CREATED",
    TRANSACTION_REQUEST_PAIED: "TRANSACTION_REQUEST_PAIED",
    TRANSACTION_REQUEST_CANCELED: "TRANSACTION_REQUEST_CANCELED",
    BANKING_TRANSACTION_CREATED: "BANKING_TRANSACTION_CREATED",
    LOGIN_VERIFICATION_CODE: "LOGIN_VERIFICATION_CODE"
}


export const QUEUE_JOBS_NAME = {
    CREATE_TRANSACTION: "CREATE_TRANSACTION",
    REMOVE_TRANSACTION_FROM_QUEUE: "REMOVE_TRANSACTION_FROM_QUEUE",
}

