services:
  anomaly:
    build:
      context: "."
      dockerfile: Dockerfile
    env_file: ".env"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build 
    command: npm run dev
    ports:
      - 8003:8003
      - 7003:7003

    networks:
      - binomia-network

networks:
  binomia-network:
    driver: bridge
